version: 0.1
        
phases:
  install:
    run-as: root
    commands:
      - apt-get install tar -y
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR_source1
      - tar -cvzf cicdtest.tar.gz .
      - cd $CODEBUILD_SRC_DIR_source2
      - tar -cvzf cicdtest2.tar.gz .
artifacts:
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR_source1
      files:
        - cicdtest.tar.gz
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR_source2
      files:
        - cicdtest2.tar.gz