version: 0.1
        
phases:
  install:
    run-as: root
    commands:
      - apt-get update -y
      - apt-get install zip -y
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR_source1
      - zip cicdtest.zip app/ $CODEBUILD_SRC_DIR_source2/app
artifacts:
  files:
    - cicdtest.zip
  name: cicdtestArtifact