version: 0.1
        
phases:
  install:
    run-as: root
    commands:
      - ls
      - apt-get update -y
  pre_build:
    run-as: root
    commands:
      - pip install waitress
      - pip install flask
